# ==============================================================================
# GitOps Environment Values: ${PRODUCT_NAME} (${ENVIRONMENT})
# Backed by argocd-gitops-tpl-library
# ==============================================================================

argocd-gitops-tpl-library:
  enabled: true

# ------------------------------------------------------------------------------
# Microservice Application Registry
# Onboard services here using 'gitops onboard helm' or 'gitops onboard manifest'
# ------------------------------------------------------------------------------
apps: {}
